### ISSUE TITLE
Kea crash when running `kea -f example.py -a omninotes.apk` in the main directory

### ISSUE THREAD

**Issue by tingsu** [ecnusse/Kea#12]
tingsu@Tings-MacBook-Pro kea-official % kea -f example.py -a omninotes.apk
{}
Traceback (most recent call last):
  File "/Users/tingsu/Library/Python/3.8/bin//kea", line 33, in <module>
    sys.exit(load_entry_point('kea', 'console_scripts', 'kea')())
  File "/Users/tingsu/Documents/Projects/kea-official/kea/start.py", line 74, in main
    start_kea(test_classes[0],setting)
IndexError: list index out of range
tingsu@Tings-MacBook-Pro kea-official % kea -f example.py -a omninotes.apk
{}
Traceback (most recent call last):
  File "/Users/tingsu/Library/Python/3.8/bin//kea", line 33, in <module>
    sys.exit(load_entry_point('kea', 'console_scripts', 'kea')())
  File "/Users/tingsu/Documents/Projects/kea-official/kea/start.py", line 74, in main
    start_kea(test_classes[0],setting)
IndexError: list index out of range
tingsu@Tings-MacBook-Pro kea-official

**Comment by XYIheng** [comment]
https://github.com/ecnusse/Kea/pull/13
